# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GameSequence.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import TrainingExample_pb2 as TrainingExample__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='GameSequence.proto',
  package='AlphaDots',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x12GameSequence.proto\x12\tAlphaDots\x1a\x15TrainingExample.proto\"W\n\x0cGameSequence\x12\r\n\x05width\x18\x01 \x02(\x05\x12\x0e\n\x06height\x18\x02 \x02(\x05\x12(\n\x04game\x18\x04 \x03(\x0b\x32\x1a.AlphaDots.TrainingExample')
  ,
  dependencies=[TrainingExample__pb2.DESCRIPTOR,])




_GAMESEQUENCE = _descriptor.Descriptor(
  name='GameSequence',
  full_name='AlphaDots.GameSequence',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='width', full_name='AlphaDots.GameSequence.width', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='AlphaDots.GameSequence.height', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='game', full_name='AlphaDots.GameSequence.game', index=2,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=143,
)

_GAMESEQUENCE.fields_by_name['game'].message_type = TrainingExample__pb2._TRAININGEXAMPLE
DESCRIPTOR.message_types_by_name['GameSequence'] = _GAMESEQUENCE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GameSequence = _reflection.GeneratedProtocolMessageType('GameSequence', (_message.Message,), dict(
  DESCRIPTOR = _GAMESEQUENCE,
  __module__ = 'GameSequence_pb2'
  # @@protoc_insertion_point(class_scope:AlphaDots.GameSequence)
  ))
_sym_db.RegisterMessage(GameSequence)


# @@protoc_insertion_point(module_scope)
