# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ModelList.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import AlphaDotsModel_pb2 as AlphaDotsModel__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ModelList.proto',
  package='AlphaDots',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x0fModelList.proto\x12\tAlphaDots\x1a\x14\x41lphaDotsModel.proto\"2\n\tModelList\x12%\n\x06models\x18\x01 \x03(\x0b\x32\x15.AlphaDots.ProtoModel\"\xa6\x01\n\x10ModelListRequest\x12;\n\x06\x61\x63tion\x18\x01 \x02(\x0e\x32+.AlphaDots.ModelListRequest.ModelListAction\x12$\n\x05model\x18\x02 \x01(\x0b\x32\x15.AlphaDots.ProtoModel\"/\n\x0fModelListAction\x12\x07\n\x03GET\x10\x01\x12\x07\n\x03\x41\x44\x44\x10\x02\x12\n\n\x06REMOVE\x10\x03')
  ,
  dependencies=[AlphaDotsModel__pb2.DESCRIPTOR,])



_MODELLISTREQUEST_MODELLISTACTION = _descriptor.EnumDescriptor(
  name='ModelListAction',
  full_name='AlphaDots.ModelListRequest.ModelListAction',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GET', index=0, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ADD', index=1, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REMOVE', index=2, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=224,
  serialized_end=271,
)
_sym_db.RegisterEnumDescriptor(_MODELLISTREQUEST_MODELLISTACTION)


_MODELLIST = _descriptor.Descriptor(
  name='ModelList',
  full_name='AlphaDots.ModelList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='models', full_name='AlphaDots.ModelList.models', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=102,
)


_MODELLISTREQUEST = _descriptor.Descriptor(
  name='ModelListRequest',
  full_name='AlphaDots.ModelListRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='action', full_name='AlphaDots.ModelListRequest.action', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='model', full_name='AlphaDots.ModelListRequest.model', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _MODELLISTREQUEST_MODELLISTACTION,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=271,
)

_MODELLIST.fields_by_name['models'].message_type = AlphaDotsModel__pb2._PROTOMODEL
_MODELLISTREQUEST.fields_by_name['action'].enum_type = _MODELLISTREQUEST_MODELLISTACTION
_MODELLISTREQUEST.fields_by_name['model'].message_type = AlphaDotsModel__pb2._PROTOMODEL
_MODELLISTREQUEST_MODELLISTACTION.containing_type = _MODELLISTREQUEST
DESCRIPTOR.message_types_by_name['ModelList'] = _MODELLIST
DESCRIPTOR.message_types_by_name['ModelListRequest'] = _MODELLISTREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ModelList = _reflection.GeneratedProtocolMessageType('ModelList', (_message.Message,), dict(
  DESCRIPTOR = _MODELLIST,
  __module__ = 'ModelList_pb2'
  # @@protoc_insertion_point(class_scope:AlphaDots.ModelList)
  ))
_sym_db.RegisterMessage(ModelList)

ModelListRequest = _reflection.GeneratedProtocolMessageType('ModelListRequest', (_message.Message,), dict(
  DESCRIPTOR = _MODELLISTREQUEST,
  __module__ = 'ModelList_pb2'
  # @@protoc_insertion_point(class_scope:AlphaDots.ModelListRequest)
  ))
_sym_db.RegisterMessage(ModelListRequest)


# @@protoc_insertion_point(module_scope)
