# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PolicyValueData.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='PolicyValueData.proto',
  package='AlphaDots',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x15PolicyValueData.proto\x12\tAlphaDots\"^\n\x0fPolicyValueData\x12\x0e\n\x06policy\x18\x01 \x03(\x01\x12\r\n\x05value\x18\x02 \x02(\x01\x12,\n\x08nextData\x18\x03 \x01(\x0b\x32\x1a.AlphaDots.PolicyValueData')
)




_POLICYVALUEDATA = _descriptor.Descriptor(
  name='PolicyValueData',
  full_name='AlphaDots.PolicyValueData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='policy', full_name='AlphaDots.PolicyValueData.policy', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='AlphaDots.PolicyValueData.value', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nextData', full_name='AlphaDots.PolicyValueData.nextData', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=130,
)

_POLICYVALUEDATA.fields_by_name['nextData'].message_type = _POLICYVALUEDATA
DESCRIPTOR.message_types_by_name['PolicyValueData'] = _POLICYVALUEDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PolicyValueData = _reflection.GeneratedProtocolMessageType('PolicyValueData', (_message.Message,), dict(
  DESCRIPTOR = _POLICYVALUEDATA,
  __module__ = 'PolicyValueData_pb2'
  # @@protoc_insertion_point(class_scope:AlphaDots.PolicyValueData)
  ))
_sym_db.RegisterMessage(PolicyValueData)


# @@protoc_insertion_point(module_scope)
