# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ProcessManagement.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ProcessManagement.proto',
  package='AlphaDots',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x17ProcessManagement.proto\x12\tAlphaDots\"\xbd\x01\n\x18ProcessManagementRequest\x12\r\n\x05model\x18\x01 \x02(\t\x12\r\n\x05width\x18\x02 \x02(\x05\x12\x0e\n\x06height\x18\x03 \x02(\x05\x12\x0b\n\x03key\x18\x04 \x02(\t\x12:\n\x06\x61\x63tion\x18\x05 \x02(\x0e\x32*.AlphaDots.ProcessManagementRequest.Action\x12\x0b\n\x03gpu\x18\x06 \x02(\x08\"\x1d\n\x06\x41\x63tion\x12\t\n\x05START\x10\x00\x12\x08\n\x04STOP\x10\x01\"6\n\x19ProcessManagementResponse\x12\x0c\n\x04port\x18\x01 \x02(\x05\x12\x0b\n\x03key\x18\x02 \x02(\t')
)



_PROCESSMANAGEMENTREQUEST_ACTION = _descriptor.EnumDescriptor(
  name='Action',
  full_name='AlphaDots.ProcessManagementRequest.Action',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='START', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STOP', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=199,
  serialized_end=228,
)
_sym_db.RegisterEnumDescriptor(_PROCESSMANAGEMENTREQUEST_ACTION)


_PROCESSMANAGEMENTREQUEST = _descriptor.Descriptor(
  name='ProcessManagementRequest',
  full_name='AlphaDots.ProcessManagementRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='model', full_name='AlphaDots.ProcessManagementRequest.model', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='width', full_name='AlphaDots.ProcessManagementRequest.width', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='AlphaDots.ProcessManagementRequest.height', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='key', full_name='AlphaDots.ProcessManagementRequest.key', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='action', full_name='AlphaDots.ProcessManagementRequest.action', index=4,
      number=5, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gpu', full_name='AlphaDots.ProcessManagementRequest.gpu', index=5,
      number=6, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PROCESSMANAGEMENTREQUEST_ACTION,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=228,
)


_PROCESSMANAGEMENTRESPONSE = _descriptor.Descriptor(
  name='ProcessManagementResponse',
  full_name='AlphaDots.ProcessManagementResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='port', full_name='AlphaDots.ProcessManagementResponse.port', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='key', full_name='AlphaDots.ProcessManagementResponse.key', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=230,
  serialized_end=284,
)

_PROCESSMANAGEMENTREQUEST.fields_by_name['action'].enum_type = _PROCESSMANAGEMENTREQUEST_ACTION
_PROCESSMANAGEMENTREQUEST_ACTION.containing_type = _PROCESSMANAGEMENTREQUEST
DESCRIPTOR.message_types_by_name['ProcessManagementRequest'] = _PROCESSMANAGEMENTREQUEST
DESCRIPTOR.message_types_by_name['ProcessManagementResponse'] = _PROCESSMANAGEMENTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ProcessManagementRequest = _reflection.GeneratedProtocolMessageType('ProcessManagementRequest', (_message.Message,), dict(
  DESCRIPTOR = _PROCESSMANAGEMENTREQUEST,
  __module__ = 'ProcessManagement_pb2'
  # @@protoc_insertion_point(class_scope:AlphaDots.ProcessManagementRequest)
  ))
_sym_db.RegisterMessage(ProcessManagementRequest)

ProcessManagementResponse = _reflection.GeneratedProtocolMessageType('ProcessManagementResponse', (_message.Message,), dict(
  DESCRIPTOR = _PROCESSMANAGEMENTRESPONSE,
  __module__ = 'ProcessManagement_pb2'
  # @@protoc_insertion_point(class_scope:AlphaDots.ProcessManagementResponse)
  ))
_sym_db.RegisterMessage(ProcessManagementResponse)


# @@protoc_insertion_point(module_scope)
