# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TrainingExample.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='TrainingExample.proto',
  package='AlphaDots',
  syntax='proto2',
  serialized_pb=_b('\n\x15TrainingExample.proto\x12\tAlphaDots\"O\n\x0fTrainingExample\x12\r\n\x05width\x18\x01 \x02(\x05\x12\x0e\n\x06height\x18\x02 \x02(\x05\x12\r\n\x05input\x18\x03 \x03(\x05\x12\x0e\n\x06output\x18\x04 \x03(\x05')
)




_TRAININGEXAMPLE = _descriptor.Descriptor(
  name='TrainingExample',
  full_name='AlphaDots.TrainingExample',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='width', full_name='AlphaDots.TrainingExample.width', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='height', full_name='AlphaDots.TrainingExample.height', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='input', full_name='AlphaDots.TrainingExample.input', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='output', full_name='AlphaDots.TrainingExample.output', index=3,
      number=4, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=115,
)

DESCRIPTOR.message_types_by_name['TrainingExample'] = _TRAININGEXAMPLE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TrainingExample = _reflection.GeneratedProtocolMessageType('TrainingExample', (_message.Message,), dict(
  DESCRIPTOR = _TRAININGEXAMPLE,
  __module__ = 'TrainingExample_pb2'
  # @@protoc_insertion_point(class_scope:AlphaDots.TrainingExample)
  ))
_sym_db.RegisterMessage(TrainingExample)


# @@protoc_insertion_point(module_scope)
